#ifndef DECORATIONSPRITE_H
#define DECORATIONSPRITE_H

#include "object_sprite.h"
#include "primitives_structs.h"

/// <summary>
/// This class is used to hold Decoration-specific methods for graphic rendering
/// </summary>
class DecorationSprite : public ObjectSprite
{
public:
	/// <summary>
	/// Constructor
	/// </summary>
	DecorationSprite();

	/// <summary>
	/// Render function
	/// </summary>
	/// <param name="data">The sprite data of the object; it is generated by the "Create" function of "ObjectSprite" class;</param>
	/// <param name="x">The X-Position of the building;</param>
	/// <param name="y">The Y-Position of the building;</param>
	/// <param name="not_placeable">Boolean; true = the building is not placeable.</param>
	void Render(SpriteData &data, float x, float y, bool not_placeable = false);

	/// <summary>
	/// Destructor
	/// </summary>
	~DecorationSprite();
};

static DecorationSprite dsprite;

#endif